export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_ITEM = 'FETCH_ITEM';
export const GET_KEYWORD = 'GET_KEYWORD';
export const FETCH_DATA_SUCCESS_TEST = 'FETCH_DATA_SUCCESS_TEST';